apiVersion: v1
kind: Pod
metadata:
  name: angular
  labels:
    app: angular
spec:
  containers:
  - name: angular
    image: richardchesterwood/k8s-fleetman-webapp-angular:release0
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
